version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-20-183-142.compute-1.amazonaws.com
            database: d1ql4u099d6n1m
            ssl: true
            user: ddgxcrqrvcgnan
            password: 884c5d1bb28385cb1b2b66b3372f9601e2a00559922e02b0895be486e7d83df7
            rawAccess: true
            port: '5432'
            migrations: true